# Generated by Django 4.2.7 on 2023-12-04 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['position']},
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('data_football_id', models.IntegerField(blank=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='stats.team')),
            ],
        ),
    ]
