# Generated by Django 4.2.7 on 2023-12-04 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_table_options_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableScorers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(blank=True)),
                ('assists', models.IntegerField(blank=True)),
                ('players', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.player')),
            ],
            options={
                'ordering': ['goals'],
            },
        ),
    ]
