# Generated by Django 4.2.7 on 2023-12-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_tablescorers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablescorers',
            options={'ordering': ['-goals']},
        ),
        migrations.AlterField(
            model_name='table',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.team'),
        ),
    ]
